# Generated by Django 3.1.1 on 2020-09-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualdetails',
            name='status_change_date',
        ),
    ]
