# Generated by Django 3.1.1 on 2020-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_remove_individualdetails_status_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19india',
            name='ConfirmedForeignNational',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='covid19india',
            name='ConfirmedIndianNational',
            field=models.IntegerField(),
        ),
    ]
